/**
 * Catalogue seed data. Prices are in RUPEES here for readability and converted to paise by the seed script.
 * Brands are fictional placeholders. Images are generated SVG placeholders (see generate-placeholder-images.ts)
 * and should be replaced with real product photography through the admin panel.
 */

export type ArtKind =
  | 'lipstick'
  | 'kajal'
  | 'compact'
  | 'nailpolish'
  | 'serum'
  | 'perfume'
  | 'lace'
  | 'earrings'
  | 'necklace'
  | 'bangles'
  | 'tikka'
  | 'ring'
  | 'anklet';

export interface SeedVariant {
  name: string;
  color?: string;
  colorHex?: string;
  size?: string;
  price?: number;
  mrp?: number;
  stock: number;
}

export interface SeedProduct {
  name: string;
  sku: string;
  category: string;
  subcategory: string;
  brand: string;
  mrp: number;
  price: number;
  gstRate: number;
  hsnCode: string;
  weightGrams: number;
  shortDescription: string;
  description: string;
  tags: string[];
  ingredients?: string;
  howToUse?: string;
  specifications: [string, string][];
  featured?: boolean;
  bestSeller?: boolean;
  newArrival?: boolean;
  art: { kind: ArtKind; colors: [string, string] };
  variants: SeedVariant[];
  createdDaysAgo: number;
}

export const categories = [
  {
    name: 'Cosmetics',
    slug: 'cosmetics',
    description: 'Long-wear lipsticks, kajal, skincare and fragrances curated for Indian skin tones.',
    imageUrl: '/images/categories/cosmetics.svg',
    subcategories: [
      ['Lipsticks', 'lipsticks'],
      ['Kajal & Eyeliner', 'kajal-eyeliner'],
      ['Face Makeup', 'face-makeup'],
      ['Nail Polish', 'nail-polish'],
      ['Skincare', 'skincare'],
      ['Fragrances', 'fragrances'],
    ],
  },
  {
    name: 'Lace',
    slug: 'lace',
    description: 'Gota patti, embroidered, crochet and beaded laces for suits, sarees and dupattas.',
    imageUrl: '/images/categories/lace.svg',
    subcategories: [
      ['Gota Patti Lace', 'gota-patti-lace'],
      ['Embroidered Lace', 'embroidered-lace'],
      ['Crochet & Cotton Lace', 'crochet-lace'],
      ['Beaded & Pearl Lace', 'beaded-lace'],
      ['Net & Organza Lace', 'net-lace'],
    ],
  },
  {
    name: 'Artificial Jewellery',
    slug: 'artificial-jewellery',
    description: 'Kundan, oxidised, American diamond and temple-style jewellery for every occasion.',
    imageUrl: '/images/categories/artificial-jewellery.svg',
    subcategories: [
      ['Earrings', 'earrings'],
      ['Necklace Sets', 'necklace-sets'],
      ['Bangles & Bracelets', 'bangles-bracelets'],
      ['Maang Tikka', 'maang-tikka'],
      ['Rings', 'rings'],
      ['Anklets', 'anklets'],
    ],
  },
] as const;

const COSMETIC_SPECS = (extra: [string, string][]): [string, string][] => [
  ...extra,
  ['Country of Origin', 'India'],
  ['Shelf Life', '36 months from manufacturing'],
];

export const products: SeedProduct[] = [
  // ───────────── Cosmetics ─────────────
  {
    name: 'Velvet Matte Lipstick',
    sku: 'KC-COS-LIP-001',
    category: 'cosmetics',
    subcategory: 'lipsticks',
    brand: 'Noor Beauty',
    mrp: 599,
    price: 449,
    gstRate: 18,
    hsnCode: '3304',
    weightGrams: 60,
    shortDescription: 'Weightless matte colour that stays put for up to 12 hours.',
    description:
      'Our best-selling Velvet Matte Lipstick glides on like a balm and sets to a soft, blurred matte finish. Enriched with vitamin E and shea butter, it keeps lips comfortable all day without drying or feathering. Highly pigmented shades have been tested on Indian skin tones — from wheatish to dusky.',
    tags: ['lipstick', 'matte', 'long lasting', 'bridal', 'lips'],
    ingredients: 'Isododecane, Dimethicone, Kaolin, Shea Butter, Tocopheryl Acetate (Vitamin E), Jojoba Oil, Mica, Iron Oxides.',
    howToUse: 'Start at the centre of your upper lip and work outward, following the contours of your mouth. Glide across the lower lip. For precise edges, line lips first.',
    specifications: COSMETIC_SPECS([
      ['Finish', 'Matte'],
      ['Net Quantity', '4.2 g'],
      ['Skin Type', 'All'],
      ['Cruelty Free', 'Yes'],
    ]),
    featured: true,
    bestSeller: true,
    art: { kind: 'lipstick', colors: ['#9B1B30', '#F3D9DC'] },
    variants: [
      { name: 'Ruby Red', color: 'Ruby Red', colorHex: '#9B1B30', stock: 40 },
      { name: 'Rosewood Nude', color: 'Rosewood', colorHex: '#A25F5B', stock: 32 },
      { name: 'Berry Wine', color: 'Berry Wine', colorHex: '#6B1D3A', stock: 18 },
      { name: 'Coral Crush', color: 'Coral', colorHex: '#E0625A', stock: 4 },
    ],
    createdDaysAgo: 120,
  },
  {
    name: 'Creamy Satin Lip Colour',
    sku: 'KC-COS-LIP-002',
    category: 'cosmetics',
    subcategory: 'lipsticks',
    brand: 'Kashif Luxe',
    mrp: 399,
    price: 299,
    gstRate: 18,
    hsnCode: '3304',
    weightGrams: 55,
    shortDescription: 'Hydrating satin finish with a hint of shine.',
    description: 'A creamy, hydrating lip colour with a satin sheen. Infused with almond oil and aloe, it melts onto lips for a comfortable, everyday look that pairs perfectly with a kajal-lined eye.',
    tags: ['lipstick', 'satin', 'everyday', 'lips'],
    ingredients: 'Ricinus Communis (Castor) Seed Oil, Candelilla Wax, Sweet Almond Oil, Aloe Barbadensis Leaf Extract, Mica, Titanium Dioxide.',
    howToUse: 'Apply directly from the bullet. Blot with a tissue and reapply for deeper colour.',
    specifications: COSMETIC_SPECS([
      ['Finish', 'Satin'],
      ['Net Quantity', '4 g'],
    ]),
    newArrival: true,
    art: { kind: 'lipstick', colors: ['#C2566B', '#FBE8EA'] },
    variants: [
      { name: 'Pink Petal', color: 'Pink', colorHex: '#D97A8E', stock: 25 },
      { name: 'Mauve Muse', color: 'Mauve', colorHex: '#9E6B7F', stock: 20 },
      { name: 'Brick Rose', color: 'Brick', colorHex: '#A5483E', stock: 15 },
    ],
    createdDaysAgo: 12,
  },
  {
    name: 'Intense Black Kajal',
    sku: 'KC-COS-KAJ-001',
    category: 'cosmetics',
    subcategory: 'kajal-eyeliner',
    brand: 'Noor Beauty',
    mrp: 249,
    price: 199,
    gstRate: 18,
    hsnCode: '3304',
    weightGrams: 30,
    shortDescription: 'Smudge-proof, waterproof kajal with 16-hour wear.',
    description: 'Deep carbon-black kajal with a smooth twist-up formula. Ophthalmologically tested, enriched with almond oil and camphor for a soothing feel. Smudge-proof and waterproof for a bold look from morning chai to late-night mehendi.',
    tags: ['kajal', 'eyes', 'waterproof', 'smudge proof', 'bestseller'],
    ingredients: 'Hydrogenated Polyisobutene, Synthetic Wax, Carbon Black, Almond Oil, Camphor, Vitamin E.',
    howToUse: 'Twist up and glide along the waterline and lash line. Smudge with the tip for a smoky effect.',
    specifications: COSMETIC_SPECS([
      ['Net Quantity', '0.35 g'],
      ['Waterproof', 'Yes'],
      ['Ophthalmologically Tested', 'Yes'],
    ]),
    bestSeller: true,
    featured: true,
    art: { kind: 'kajal', colors: ['#1E1A1D', '#E9E1DC'] },
    variants: [{ name: 'Standard', stock: 120 }],
    createdDaysAgo: 200,
  },
  {
    name: 'Liquid Wing Eyeliner',
    sku: 'KC-COS-KAJ-002',
    category: 'cosmetics',
    subcategory: 'kajal-eyeliner',
    brand: 'Mehr Cosmetics',
    mrp: 349,
    price: 279,
    gstRate: 18,
    hsnCode: '3304',
    weightGrams: 35,
    shortDescription: 'Felt-tip precision for the perfect wing.',
    description: 'A fine felt-tip liquid liner for crisp wings and graphic looks. Quick-drying and transfer-resistant with a glossy black finish.',
    tags: ['eyeliner', 'eyes', 'liquid liner', 'wing'],
    ingredients: 'Aqua, Styrene/Acrylates Copolymer, Butylene Glycol, Black 2 (CI 77266), Phenoxyethanol.',
    howToUse: 'Starting at the inner corner, draw a thin line along the lash line and flick outwards at the outer corner.',
    specifications: COSMETIC_SPECS([
      ['Net Quantity', '1.2 ml'],
      ['Tip', 'Felt tip'],
    ]),
    art: { kind: 'kajal', colors: ['#2B2126', '#EFE6F0'] },
    variants: [
      { name: 'Jet Black', color: 'Black', colorHex: '#111111', stock: 45 },
      { name: 'Midnight Blue', color: 'Blue', colorHex: '#1F2F5C', stock: 12 },
    ],
    createdDaysAgo: 60,
  },
  {
    name: 'Silk Finish Compact Powder',
    sku: 'KC-COS-FAC-001',
    category: 'cosmetics',
    subcategory: 'face-makeup',
    brand: 'Kashif Luxe',
    mrp: 499,
    price: 379,
    gstRate: 18,
    hsnCode: '3304',
    weightGrams: 90,
    shortDescription: 'Oil-control compact with SPF 15 for a natural matte finish.',
    description: 'A finely milled pressed powder that controls shine, blurs pores and evens out skin tone with a soft-focus, natural finish. SPF 15 protects against everyday sun exposure.',
    tags: ['compact', 'face', 'spf', 'oil control'],
    ingredients: 'Talc, Mica, Zinc Stearate, Titanium Dioxide, Dimethicone, Iron Oxides.',
    howToUse: 'Press the puff into the powder and pat onto the T-zone and cheeks. Reapply through the day to control shine.',
    specifications: COSMETIC_SPECS([
      ['Net Quantity', '9 g'],
      ['SPF', '15'],
      ['Finish', 'Matte'],
    ]),
    art: { kind: 'compact', colors: ['#D8B08C', '#F7ECE3'] },
    variants: [
      { name: 'Ivory 01', color: 'Ivory', colorHex: '#EBD2B8', stock: 22 },
      { name: 'Natural Beige 02', color: 'Beige', colorHex: '#D6AE8B', stock: 30 },
      { name: 'Honey 03', color: 'Honey', colorHex: '#B98457', stock: 3 },
    ],
    createdDaysAgo: 90,
  },
  {
    name: 'Glow Liquid Foundation',
    sku: 'KC-COS-FAC-002',
    category: 'cosmetics',
    subcategory: 'face-makeup',
    brand: 'Noor Beauty',
    mrp: 799,
    price: 599,
    gstRate: 18,
    hsnCode: '3304',
    weightGrams: 120,
    shortDescription: 'Buildable medium coverage with a luminous finish.',
    description: 'Lightweight, breathable foundation with hyaluronic acid for a dewy, lit-from-within glow. Buildable from sheer to medium coverage and formulated for warm Indian undertones.',
    tags: ['foundation', 'face', 'dewy', 'bridal'],
    ingredients: 'Aqua, Cyclopentasiloxane, Glycerin, Sodium Hyaluronate, Niacinamide, Titanium Dioxide, Iron Oxides.',
    howToUse: 'Dot on forehead, cheeks and chin; blend outwards with a damp sponge or brush.',
    specifications: COSMETIC_SPECS([
      ['Net Quantity', '30 ml'],
      ['Coverage', 'Medium, buildable'],
      ['Finish', 'Dewy'],
    ]),
    newArrival: true,
    featured: true,
    art: { kind: 'serum', colors: ['#C89B78', '#F6EDE6'] },
    variants: [
      { name: 'Warm Ivory', color: 'Warm Ivory', colorHex: '#E3C0A0', stock: 14 },
      { name: 'Golden Sand', color: 'Golden Sand', colorHex: '#C79A70', stock: 18 },
      { name: 'Caramel', color: 'Caramel', colorHex: '#9C6B45', stock: 9 },
    ],
    createdDaysAgo: 8,
  },
  {
    name: 'Gel Shine Nail Polish',
    sku: 'KC-COS-NAI-001',
    category: 'cosmetics',
    subcategory: 'nail-polish',
    brand: 'Mehr Cosmetics',
    mrp: 199,
    price: 149,
    gstRate: 18,
    hsnCode: '3304',
    weightGrams: 45,
    shortDescription: 'Gel-like shine without a UV lamp. Chip resistant for 7 days.',
    description: 'High-shine, quick-dry nail colour with a wide brush for streak-free application in one to two coats. Toluene and formaldehyde free.',
    tags: ['nail polish', 'nails', 'gel', 'quick dry'],
    ingredients: 'Butyl Acetate, Ethyl Acetate, Nitrocellulose, Adipic Acid/Neopentyl Glycol/Trimellitic Anhydride Copolymer, Pigments.',
    howToUse: 'Apply two thin coats on clean nails, allowing each to dry for 2 minutes. Finish with a top coat for extra shine.',
    specifications: COSMETIC_SPECS([
      ['Net Quantity', '9 ml'],
      ['Free From', 'Toluene, Formaldehyde, DBP'],
    ]),
    bestSeller: true,
    art: { kind: 'nailpolish', colors: ['#B0203A', '#FCE6EA'] },
    variants: [
      { name: 'Classic Red', color: 'Red', colorHex: '#B0203A', stock: 50 },
      { name: 'Blush Pink', color: 'Pink', colorHex: '#E8A0B0', stock: 40 },
      { name: 'Plum', color: 'Plum', colorHex: '#5B1A32', stock: 35 },
      { name: 'Nude Latte', color: 'Nude', colorHex: '#CFA58A', stock: 0 },
    ],
    createdDaysAgo: 150,
  },
  {
    name: 'Kumkumadi Glow Face Serum',
    sku: 'KC-COS-SKN-001',
    category: 'cosmetics',
    subcategory: 'skincare',
    brand: 'Kashif Luxe',
    mrp: 899,
    price: 649,
    gstRate: 18,
    hsnCode: '3304',
    weightGrams: 110,
    shortDescription: 'Ayurvedic saffron serum for radiant, even-toned skin.',
    description: 'Inspired by the ancient Kumkumadi tailam, this lightweight serum blends saffron, vitamin C and niacinamide to fade dark spots and restore natural radiance — without greasiness.',
    tags: ['serum', 'skincare', 'kumkumadi', 'vitamin c', 'glow'],
    ingredients: 'Aqua, Niacinamide, Crocus Sativus (Saffron) Extract, Ascorbyl Glucoside, Licorice Root Extract, Sodium Hyaluronate, Sandalwood Oil.',
    howToUse: 'After cleansing, apply 3–4 drops to face and neck. Pat gently. Use morning and night; follow with sunscreen during the day.',
    specifications: COSMETIC_SPECS([
      ['Net Quantity', '30 ml'],
      ['Skin Type', 'All, including sensitive'],
      ['Paraben Free', 'Yes'],
    ]),
    featured: true,
    bestSeller: true,
    art: { kind: 'serum', colors: ['#D08A2C', '#FBF0DE'] },
    variants: [{ name: 'Standard', stock: 60 }],
    createdDaysAgo: 100,
  },
  {
    name: 'Rose & Aloe Hydrating Face Wash',
    sku: 'KC-COS-SKN-002',
    category: 'cosmetics',
    subcategory: 'skincare',
    brand: 'Noor Beauty',
    mrp: 299,
    price: 229,
    gstRate: 18,
    hsnCode: '3304',
    weightGrams: 130,
    shortDescription: 'Gentle, soap-free daily cleanser.',
    description: 'A soap-free gel cleanser with real rose water and aloe vera that removes dirt and makeup while keeping skin soft and hydrated.',
    tags: ['face wash', 'skincare', 'rose', 'aloe'],
    ingredients: 'Rosa Damascena Flower Water, Aloe Barbadensis Leaf Juice, Cocamidopropyl Betaine, Glycerin, Allantoin.',
    howToUse: 'Massage a small amount onto damp face, rinse thoroughly. Use twice daily.',
    specifications: COSMETIC_SPECS([['Net Quantity', '100 ml']]),
    art: { kind: 'serum', colors: ['#D9738A', '#FDEEF1'] },
    variants: [
      { name: '100 ml', size: '100 ml', stock: 70 },
      { name: '200 ml', size: '200 ml', price: 399, mrp: 499, stock: 30 },
    ],
    createdDaysAgo: 45,
  },
  {
    name: 'Oud Royale Attar',
    sku: 'KC-COS-FRA-001',
    category: 'cosmetics',
    subcategory: 'fragrances',
    brand: 'Kashif Luxe',
    mrp: 1299,
    price: 899,
    gstRate: 18,
    hsnCode: '3303',
    weightGrams: 80,
    shortDescription: 'Alcohol-free, long lasting concentrated perfume oil.',
    description: 'A rich, woody attar with notes of oud, amber and a whisper of rose. Alcohol-free and hand-blended in small batches, a single swipe lasts all day.',
    tags: ['attar', 'perfume', 'fragrance', 'oud', 'gift', 'eid'],
    ingredients: 'Blend of natural and nature-identical essential oils in a sandalwood base. Alcohol free.',
    howToUse: 'Apply a small amount to pulse points — wrists, behind ears and neck. Do not rub.',
    specifications: [
      ['Net Quantity', '12 ml'],
      ['Fragrance Family', 'Woody Oriental'],
      ['Alcohol Free', 'Yes'],
      ['Country of Origin', 'India'],
    ],
    featured: true,
    art: { kind: 'perfume', colors: ['#6B3A1E', '#F5E6D3'] },
    variants: [
      { name: '6 ml', size: '6 ml', price: 549, mrp: 799, stock: 25 },
      { name: '12 ml', size: '12 ml', stock: 20 },
    ],
    createdDaysAgo: 30,
  },
  {
    name: 'Jasmine Bloom Eau de Parfum',
    sku: 'KC-COS-FRA-002',
    category: 'cosmetics',
    subcategory: 'fragrances',
    brand: 'Noor Beauty',
    mrp: 999,
    price: 749,
    gstRate: 18,
    hsnCode: '3303',
    weightGrams: 180,
    shortDescription: 'Fresh mogra and white musk.',
    description: 'A fresh floral fragrance inspired by strings of mogra in summer. Notes of jasmine, bergamot and white musk make it perfect for daytime wear.',
    tags: ['perfume', 'fragrance', 'floral', 'gift'],
    ingredients: 'Alcohol Denat., Parfum, Aqua, Benzyl Salicylate, Linalool.',
    howToUse: 'Spray from 15 cm onto pulse points.',
    specifications: [
      ['Net Quantity', '50 ml'],
      ['Fragrance Family', 'Floral'],
      ['Country of Origin', 'India'],
    ],
    newArrival: true,
    art: { kind: 'perfume', colors: ['#B98AA6', '#F8EEF4'] },
    variants: [{ name: 'Standard', stock: 35 }],
    createdDaysAgo: 5,
  },

  // ───────────── Lace ─────────────
  {
    name: 'Golden Gota Patti Border Lace',
    sku: 'KC-LAC-GOT-001',
    category: 'lace',
    subcategory: 'gota-patti-lace',
    brand: 'Zari Craft',
    mrp: 399,
    price: 299,
    gstRate: 5,
    hsnCode: '5804',
    weightGrams: 150,
    shortDescription: 'Traditional Rajasthani gota patti on satin base — 9 metre roll.',
    description: 'Handcrafted gota patti lace with shimmering leaf motifs on a satin base. Adds a festive, royal touch to lehengas, dupattas and suit necklines. Sold as a 9-metre roll.',
    tags: ['gota patti', 'lace', 'border', 'wedding', 'dupatta'],
    specifications: [
      ['Material', 'Satin base with metallic gota'],
      ['Length', '9 metres'],
      ['Wash Care', 'Dry clean recommended'],
      ['Country of Origin', 'India'],
    ],
    featured: true,
    bestSeller: true,
    art: { kind: 'lace', colors: ['#C9A227', '#FBF4DE'] },
    variants: [
      { name: '1 inch · Gold', color: 'Gold', colorHex: '#C9A227', size: '1 inch', stock: 60 },
      { name: '2 inch · Gold', color: 'Gold', colorHex: '#C9A227', size: '2 inch', price: 449, mrp: 599, stock: 40 },
      { name: '2 inch · Silver', color: 'Silver', colorHex: '#BFC1C2', size: '2 inch', price: 449, mrp: 599, stock: 25 },
    ],
    createdDaysAgo: 180,
  },
  {
    name: 'Mirror Work Gota Lace',
    sku: 'KC-LAC-GOT-002',
    category: 'lace',
    subcategory: 'gota-patti-lace',
    brand: 'Zari Craft',
    mrp: 549,
    price: 429,
    gstRate: 5,
    hsnCode: '5804',
    weightGrams: 180,
    shortDescription: 'Gota with real mirror accents — 5 metre roll.',
    description: 'Festive gota lace studded with small mirrors and zari highlights. Perfect for Navratri chaniya cholis and mehendi outfits.',
    tags: ['gota patti', 'mirror', 'lace', 'navratri', 'festive'],
    specifications: [
      ['Material', 'Tissue base, mirror, zari'],
      ['Length', '5 metres'],
      ['Width', '1.5 inch'],
    ],
    newArrival: true,
    art: { kind: 'lace', colors: ['#B8875A', '#F7EFE6'] },
    variants: [
      { name: 'Gold Mirror', color: 'Gold', colorHex: '#C9A227', stock: 30 },
      { name: 'Rani Pink Mirror', color: 'Pink', colorHex: '#D6336C', stock: 20 },
    ],
    createdDaysAgo: 10,
  },
  {
    name: 'Floral Thread Embroidered Lace',
    sku: 'KC-LAC-EMB-001',
    category: 'lace',
    subcategory: 'embroidered-lace',
    brand: 'Rangoli Lace House',
    mrp: 349,
    price: 249,
    gstRate: 5,
    hsnCode: '5810',
    weightGrams: 120,
    shortDescription: 'Multi-colour resham embroidery on georgette — 9 metres.',
    description: 'Delicate resham thread embroidery in a vine-and-flower pattern on a soft georgette base. Ideal for kurti hems, sleeves and dupatta borders.',
    tags: ['embroidered', 'lace', 'resham', 'kurti', 'border'],
    specifications: [
      ['Material', 'Georgette with resham thread'],
      ['Length', '9 metres'],
      ['Width', '1.25 inch'],
      ['Wash Care', 'Gentle hand wash'],
    ],
    bestSeller: true,
    art: { kind: 'lace', colors: ['#7A2E4A', '#F9EAF0'] },
    variants: [
      { name: 'Maroon Multi', color: 'Maroon', colorHex: '#7A2E4A', stock: 45 },
      { name: 'Ivory Multi', color: 'Ivory', colorHex: '#F2E8D5', stock: 38 },
      { name: 'Bottle Green', color: 'Green', colorHex: '#1E5B45', stock: 20 },
    ],
    createdDaysAgo: 140,
  },
  {
    name: 'Zari Paisley Cutwork Lace',
    sku: 'KC-LAC-EMB-002',
    category: 'lace',
    subcategory: 'embroidered-lace',
    brand: 'Zari Craft',
    mrp: 699,
    price: 499,
    gstRate: 12,
    hsnCode: '5810',
    weightGrams: 160,
    shortDescription: 'Scalloped cutwork with antique zari — 4.5 metres.',
    description: 'A statement cutwork lace with antique zari paisleys and a scalloped edge. Elevates sarees, lehenga hems and bridal dupattas.',
    tags: ['zari', 'cutwork', 'lace', 'bridal', 'saree'],
    specifications: [
      ['Material', 'Net base, antique zari'],
      ['Length', '4.5 metres'],
      ['Width', '3 inch'],
    ],
    featured: true,
    art: { kind: 'lace', colors: ['#A0782C', '#F6EFE2'] },
    variants: [{ name: 'Antique Gold', color: 'Gold', colorHex: '#A0782C', stock: 16 }],
    createdDaysAgo: 75,
  },
  {
    name: 'Handmade Cotton Crochet Lace',
    sku: 'KC-LAC-CRO-001',
    category: 'lace',
    subcategory: 'crochet-lace',
    brand: 'Rangoli Lace House',
    mrp: 199,
    price: 149,
    gstRate: 5,
    hsnCode: '5804',
    weightGrams: 90,
    shortDescription: '100% cotton crochet trim — 9 metres.',
    description: 'Soft, breathable cotton crochet lace with a classic scalloped design. Great for cotton kurtis, home linen, pillow covers and craft projects.',
    tags: ['crochet', 'cotton', 'lace', 'craft', 'kurti'],
    specifications: [
      ['Material', '100% Cotton'],
      ['Length', '9 metres'],
      ['Wash Care', 'Machine wash cold'],
    ],
    art: { kind: 'lace', colors: ['#8C7B6B', '#FAF6F0'] },
    variants: [
      { name: 'White · 1 inch', color: 'White', colorHex: '#FFFFFF', size: '1 inch', stock: 80 },
      { name: 'Off White · 1 inch', color: 'Off White', colorHex: '#F4EDE0', size: '1 inch', stock: 65 },
      { name: 'White · 2 inch', color: 'White', colorHex: '#FFFFFF', size: '2 inch', price: 199, mrp: 249, stock: 40 },
    ],
    createdDaysAgo: 220,
  },
  {
    name: 'Pearl Drop Beaded Lace',
    sku: 'KC-LAC-BEA-001',
    category: 'lace',
    subcategory: 'beaded-lace',
    brand: 'Zari Craft',
    mrp: 799,
    price: 599,
    gstRate: 12,
    hsnCode: '5810',
    weightGrams: 200,
    shortDescription: 'Hand-stitched pearl drops with sequin base — 3 metres.',
    description: 'An elegant hand-stitched lace with hanging faux pearl drops and a subtle sequin base. Adds movement and luxury to dupattas, blouse sleeves and lehenga hems.',
    tags: ['pearl', 'beaded', 'lace', 'bridal', 'handmade'],
    specifications: [
      ['Material', 'Net, faux pearls, sequins'],
      ['Length', '3 metres'],
      ['Work', 'Hand-stitched'],
    ],
    newArrival: true,
    featured: true,
    art: { kind: 'lace', colors: ['#B7A58E', '#FBF8F3'] },
    variants: [
      { name: 'Ivory Pearl', color: 'Ivory', colorHex: '#F2E8D5', stock: 12 },
      { name: 'Champagne', color: 'Champagne', colorHex: '#E5CFA6', stock: 2 },
    ],
    createdDaysAgo: 3,
  },
  {
    name: 'Scalloped Organza Net Lace',
    sku: 'KC-LAC-NET-001',
    category: 'lace',
    subcategory: 'net-lace',
    brand: 'Rangoli Lace House',
    mrp: 299,
    price: 219,
    gstRate: 5,
    hsnCode: '5804',
    weightGrams: 100,
    shortDescription: 'Sheer organza with sequin scallops — 9 metres.',
    description: 'Lightweight organza net lace finished with sequin-outlined scallops. Adds a soft, dreamy finish to anarkalis and gowns.',
    tags: ['net', 'organza', 'lace', 'sequin'],
    specifications: [
      ['Material', 'Organza net, sequins'],
      ['Length', '9 metres'],
      ['Width', '2 inch'],
    ],
    art: { kind: 'lace', colors: ['#C47A8B', '#FCF0F3'] },
    variants: [
      { name: 'Blush Pink', color: 'Pink', colorHex: '#E8B4BF', stock: 28 },
      { name: 'Powder Blue', color: 'Blue', colorHex: '#AFC6DB', stock: 22 },
      { name: 'Mint', color: 'Green', colorHex: '#B5D9C7', stock: 18 },
    ],
    createdDaysAgo: 55,
  },

  // ───────────── Artificial Jewellery ─────────────
  {
    name: 'Kundan Chandbali Earrings',
    sku: 'KC-JWL-EAR-001',
    category: 'artificial-jewellery',
    subcategory: 'earrings',
    brand: 'Shringar Jewels',
    mrp: 1199,
    price: 699,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 70,
    shortDescription: 'Crescent chandbalis with kundan stones and pearl hangings.',
    description: 'Statement chandbali earrings handcrafted with kundan stones, meenakari detailing and delicate faux pearl drops. Lightweight enough to wear through a long wedding day.',
    tags: ['earrings', 'kundan', 'chandbali', 'bridal', 'wedding', 'jewellery'],
    specifications: [
      ['Base Metal', 'Brass'],
      ['Plating', 'Gold plated'],
      ['Stone', 'Kundan, faux pearl'],
      ['Closure', 'Push back'],
      ['Weight', '28 g (pair)'],
    ],
    featured: true,
    bestSeller: true,
    art: { kind: 'earrings', colors: ['#C9A227', '#FBF1E1'] },
    variants: [
      { name: 'Gold · White Kundan', color: 'Gold', colorHex: '#C9A227', stock: 20 },
      { name: 'Gold · Ruby Kundan', color: 'Ruby', colorHex: '#9B1B30', stock: 15 },
      { name: 'Gold · Emerald Kundan', color: 'Emerald', colorHex: '#1E6B4F', stock: 6 },
    ],
    createdDaysAgo: 160,
  },
  {
    name: 'Oxidised Silver Jhumka',
    sku: 'KC-JWL-EAR-002',
    category: 'artificial-jewellery',
    subcategory: 'earrings',
    brand: 'Shringar Jewels',
    mrp: 599,
    price: 349,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 50,
    shortDescription: 'Boho oxidised jhumkas with ghungroo bells.',
    description: 'Classic temple-style oxidised jhumkas with intricate carvings and tiny ghungroo bells. Pairs beautifully with cotton sarees, kurtas and indo-western outfits.',
    tags: ['jhumka', 'oxidised', 'earrings', 'boho', 'everyday', 'jewellery'],
    specifications: [
      ['Base Metal', 'Alloy'],
      ['Plating', 'Oxidised silver'],
      ['Closure', 'Hook'],
    ],
    bestSeller: true,
    art: { kind: 'earrings', colors: ['#8A8D91', '#F1F1F0'] },
    variants: [{ name: 'Standard', stock: 55 }],
    createdDaysAgo: 210,
  },
  {
    name: 'American Diamond Stud Earrings',
    sku: 'KC-JWL-EAR-003',
    category: 'artificial-jewellery',
    subcategory: 'earrings',
    brand: 'Shringar Jewels',
    mrp: 799,
    price: 499,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 30,
    shortDescription: 'Sparkling AD floral studs for everyday elegance.',
    description: 'Brilliant-cut American diamond studs set in a floral cluster. Hypoallergenic and nickel-free — perfect for office, parties and gifting.',
    tags: ['studs', 'american diamond', 'ad', 'earrings', 'gift', 'jewellery'],
    specifications: [
      ['Base Metal', 'Brass'],
      ['Plating', 'Rhodium / Rose gold'],
      ['Stone', 'Cubic zirconia (AD)'],
      ['Nickel Free', 'Yes'],
    ],
    newArrival: true,
    art: { kind: 'earrings', colors: ['#B7C3D0', '#F4F6F9'] },
    variants: [
      { name: 'Silver Tone', color: 'Silver', colorHex: '#C0C4C8', stock: 30 },
      { name: 'Rose Gold Tone', color: 'Rose Gold', colorHex: '#C98B77', stock: 26 },
    ],
    createdDaysAgo: 15,
  },
  {
    name: 'Royal Kundan Bridal Necklace Set',
    sku: 'KC-JWL-NEC-001',
    category: 'artificial-jewellery',
    subcategory: 'necklace-sets',
    brand: 'Shringar Jewels',
    mrp: 4999,
    price: 2799,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 350,
    shortDescription: 'Choker-style kundan necklace with matching earrings and tikka.',
    description: 'A regal bridal set featuring a kundan choker with pearl strings, matching earrings and maang tikka. Finished with an adjustable dori for a comfortable fit. Arrives in a gift-ready velvet box.',
    tags: ['necklace', 'bridal', 'kundan', 'set', 'wedding', 'choker', 'jewellery'],
    specifications: [
      ['Includes', 'Necklace, pair of earrings, maang tikka'],
      ['Base Metal', 'Brass'],
      ['Plating', '22K gold plated'],
      ['Closure', 'Adjustable dori'],
    ],
    featured: true,
    bestSeller: true,
    art: { kind: 'necklace', colors: ['#B8872F', '#FBF3E3'] },
    variants: [
      { name: 'Ruby Green', color: 'Ruby Green', colorHex: '#8B1E3F', stock: 8 },
      { name: 'Pastel Pink', color: 'Pink', colorHex: '#E6A4B4', stock: 5 },
    ],
    createdDaysAgo: 130,
  },
  {
    name: 'Temple Lakshmi Coin Necklace',
    sku: 'KC-JWL-NEC-002',
    category: 'artificial-jewellery',
    subcategory: 'necklace-sets',
    brand: 'Shringar Jewels',
    mrp: 2499,
    price: 1599,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 260,
    shortDescription: 'South-Indian temple design with Lakshmi coin motifs.',
    description: 'A long temple-style haram with Goddess Lakshmi coins, matte gold finish and ruby-green accents. Paired with matching jhumkas.',
    tags: ['temple', 'necklace', 'coin', 'haram', 'festive', 'jewellery'],
    specifications: [
      ['Includes', 'Necklace, pair of earrings'],
      ['Plating', 'Matte gold'],
      ['Length', '24 inch'],
    ],
    art: { kind: 'necklace', colors: ['#A57A2C', '#F8F0E1'] },
    variants: [{ name: 'Standard', stock: 12 }],
    createdDaysAgo: 85,
  },
  {
    name: 'Minimal Pearl Layered Necklace',
    sku: 'KC-JWL-NEC-003',
    category: 'artificial-jewellery',
    subcategory: 'necklace-sets',
    brand: 'Kashif Collection',
    mrp: 999,
    price: 649,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 90,
    shortDescription: 'Two-layer freshwater-style pearl necklace.',
    description: 'A modern two-layer necklace with lustrous faux pearls on a gold-tone chain. Effortlessly pairs with western and ethnic wear.',
    tags: ['pearl', 'necklace', 'minimal', 'layered', 'gift', 'jewellery'],
    specifications: [
      ['Base Metal', 'Alloy'],
      ['Length', '16 + 18 inch'],
      ['Closure', 'Lobster clasp'],
    ],
    newArrival: true,
    art: { kind: 'necklace', colors: ['#CDBBA0', '#FAF7F2'] },
    variants: [{ name: 'Standard', stock: 25 }],
    createdDaysAgo: 20,
  },
  {
    name: 'Rajwadi Gold Plated Bangles (Set of 4)',
    sku: 'KC-JWL-BAN-001',
    category: 'artificial-jewellery',
    subcategory: 'bangles-bracelets',
    brand: 'Shringar Jewels',
    mrp: 1499,
    price: 999,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 220,
    shortDescription: 'Intricately carved kada-style bangles with stone work.',
    description: 'A set of four Rajwadi bangles with antique gold finish, carved motifs and kundan stones. Screw-open design for easy wearing.',
    tags: ['bangles', 'kada', 'rajwadi', 'bridal', 'jewellery'],
    specifications: [
      ['Set Of', '4'],
      ['Plating', 'Antique gold'],
      ['Opening', 'Screw open'],
    ],
    featured: true,
    art: { kind: 'bangles', colors: ['#B8872F', '#FBF1E1'] },
    variants: [
      { name: 'Size 2.4', size: '2.4', stock: 10 },
      { name: 'Size 2.6', size: '2.6', stock: 14 },
      { name: 'Size 2.8', size: '2.8', stock: 7 },
    ],
    createdDaysAgo: 110,
  },
  {
    name: 'Glass & Stone Bangle Stack',
    sku: 'KC-JWL-BAN-002',
    category: 'artificial-jewellery',
    subcategory: 'bangles-bracelets',
    brand: 'Kashif Collection',
    mrp: 499,
    price: 299,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 300,
    shortDescription: 'Colourful 24-piece glass bangle stack with stone kadas.',
    description: 'Traditional glass bangles in festive colours with two stone-studded kadas. A must-have for Karwa Chauth, Teej and Eid.',
    tags: ['bangles', 'glass', 'festive', 'eid', 'teej', 'jewellery'],
    specifications: [
      ['Pieces', '24 glass + 2 kadas'],
      ['Material', 'Glass, alloy'],
    ],
    bestSeller: true,
    art: { kind: 'bangles', colors: ['#B0203A', '#FDEBEE'] },
    variants: [
      { name: 'Maroon · 2.4', color: 'Maroon', colorHex: '#7A1F2E', size: '2.4', stock: 22 },
      { name: 'Maroon · 2.6', color: 'Maroon', colorHex: '#7A1F2E', size: '2.6', stock: 25 },
      { name: 'Green · 2.4', color: 'Green', colorHex: '#1E6B4F', size: '2.4', stock: 18 },
      { name: 'Green · 2.6', color: 'Green', colorHex: '#1E6B4F', size: '2.6', stock: 0 },
    ],
    createdDaysAgo: 190,
  },
  {
    name: 'Polki Maang Tikka',
    sku: 'KC-JWL-TIK-001',
    category: 'artificial-jewellery',
    subcategory: 'maang-tikka',
    brand: 'Shringar Jewels',
    mrp: 899,
    price: 549,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 40,
    shortDescription: 'Polki-style tikka with pearl fringe.',
    description: 'A graceful maang tikka with a polki-style centrepiece and a pearl fringe. Adjustable chain with a secure hook.',
    tags: ['maang tikka', 'tikka', 'polki', 'bridal', 'jewellery'],
    specifications: [
      ['Plating', 'Gold'],
      ['Stone', 'Polki-style glass, faux pearls'],
    ],
    art: { kind: 'tikka', colors: ['#C9A227', '#FBF4E2'] },
    variants: [
      { name: 'White', color: 'White', colorHex: '#F5F1E8', stock: 18 },
      { name: 'Pink', color: 'Pink', colorHex: '#E6A4B4', stock: 11 },
    ],
    createdDaysAgo: 70,
  },
  {
    name: 'Adjustable AD Cocktail Ring',
    sku: 'KC-JWL-RIN-001',
    category: 'artificial-jewellery',
    subcategory: 'rings',
    brand: 'Shringar Jewels',
    mrp: 499,
    price: 299,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 20,
    shortDescription: 'Oversized cocktail ring with a centre solitaire.',
    description: 'A glamorous cocktail ring with a large centre stone surrounded by American diamonds. Adjustable band fits most fingers.',
    tags: ['ring', 'cocktail', 'american diamond', 'party', 'jewellery'],
    specifications: [
      ['Size', 'Adjustable'],
      ['Plating', 'Rhodium'],
    ],
    art: { kind: 'ring', colors: ['#5B6C8F', '#EEF1F6'] },
    variants: [
      { name: 'Sapphire Blue', color: 'Blue', colorHex: '#23408E', stock: 20 },
      { name: 'Emerald Green', color: 'Green', colorHex: '#1E6B4F', stock: 16 },
      { name: 'Ruby Red', color: 'Red', colorHex: '#9B1B30', stock: 14 },
    ],
    createdDaysAgo: 40,
  },
  {
    name: 'Silver Tone Ghungroo Payal',
    sku: 'KC-JWL-ANK-001',
    category: 'artificial-jewellery',
    subcategory: 'anklets',
    brand: 'Kashif Collection',
    mrp: 699,
    price: 449,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 80,
    shortDescription: 'Traditional payal pair with tinkling ghungroos.',
    description: 'A pair of silver-tone anklets with delicate ghungroo bells and an adjustable S-hook. Comfortable for daily wear.',
    tags: ['anklet', 'payal', 'ghungroo', 'silver', 'jewellery'],
    specifications: [
      ['Includes', '1 pair'],
      ['Length', '10.5 inch (adjustable)'],
      ['Plating', 'Silver'],
    ],
    art: { kind: 'anklet', colors: ['#9EA3A8', '#F3F4F5'] },
    variants: [{ name: 'Standard', stock: 40 }],
    createdDaysAgo: 95,
  },
  {
    name: 'Gold Plated Charm Bracelet',
    sku: 'KC-JWL-BAN-003',
    category: 'artificial-jewellery',
    subcategory: 'bangles-bracelets',
    brand: 'Kashif Collection',
    mrp: 799,
    price: 529,
    gstRate: 3,
    hsnCode: '7117',
    weightGrams: 40,
    shortDescription: 'Dainty bracelet with evil-eye and heart charms.',
    description: 'A dainty gold-plated chain bracelet with evil-eye, heart and pearl charms. Anti-tarnish coating keeps it shining longer.',
    tags: ['bracelet', 'charm', 'evil eye', 'gift', 'jewellery'],
    specifications: [
      ['Plating', '18K gold plated, anti-tarnish'],
      ['Length', '6.5 + 1.5 inch extender'],
    ],
    newArrival: true,
    art: { kind: 'bangles', colors: ['#C9A227', '#FBF6E8'] },
    variants: [{ name: 'Standard', stock: 35 }],
    createdDaysAgo: 6,
  },
];

export const customers = [
  { name: 'Priya Sharma', email: 'priya@example.com', phone: '9876543210', city: 'Lucknow', pincode: '226001' },
  { name: 'Aisha Khan', email: 'aisha@example.com', phone: '9812345678', city: 'Shahjahanpur', pincode: '242001' },
  { name: 'Neha Verma', email: 'neha@example.com', phone: '9898989898', city: 'Bareilly', pincode: '243001' },
  { name: 'Fatima Siddiqui', email: 'fatima@example.com', phone: '9765432109', city: 'Delhi', pincode: '110025', state: 'Delhi' },
  { name: 'Rohan Gupta', email: 'rohan@example.com', phone: '9123456780', city: 'Mumbai', pincode: '400050', state: 'Maharashtra' },
];

export const reviewTexts: Array<{ rating: number; title: string; body: string }> = [
  { rating: 5, title: 'Absolutely love it!', body: 'The quality is amazing for the price. Packaging was beautiful and delivery was quick. Will definitely order again.' },
  { rating: 5, title: 'Perfect for my sister’s wedding', body: 'Looked exactly like the pictures, everyone asked me where I bought it from. Highly recommended!' },
  { rating: 4, title: 'Very good quality', body: 'Nice finish and comfortable to use. Colour is slightly different from the photo but still lovely.' },
  { rating: 5, title: 'Stays all day', body: 'Wore it for a full day event and it did not budge. Great value and fast delivery to my city.' },
  { rating: 4, title: 'Value for money', body: 'Good product, well packed. Took 4 days to arrive but the quality made up for it.' },
  { rating: 3, title: 'Decent', body: 'Product is okay. Expected a bit more shine, but it works fine for daily use.' },
];
